### ISSUE TITLE
不知道用什么节点

### ISSUE THREAD

**Issue by joycechu1990** [HaveF/practicalDA#3]
**描述问题**
> 想要把两张表合并不知道用什么节点

表1：
![image](https://user-images.githubusercontent.com/49674932/56193408-26c53d00-6063-11e9-87ed-976ef40c66e0.png)

表2：

![image](https://user-images.githubusercontent.com/49674932/56193457-4197b180-6063-11e9-9165-4e7c6afc5112.png)

我要根据platform,country,categ_key 三个字段，把表1 的数据合并到表二
同时表二的数据不会减少

合并后表二应该是如下字段：
platform,country,categ_key ，Job_id,crawl_week,crawl_total_page,crawl_total_item,show_item_num,web_total_item,web_total_page

**Comment by HaveF** [comment]
[基础数据操作之四，从SQL的case，group by，join 到工具 KNIME](https://havef.github.io/practicalda/03%20KNIME%20%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%90%E5%9F%BA%E7%A1%80/05%20%E5%9F%BA%E7%A1%80%E6%95%B0%E6%8D%AE%E6%93%8D%E4%BD%9C%E4%B9%8B%E5%9B%9B%EF%BC%8C%E4%BB%8ESQL%E7%9A%84case%EF%BC%8Cgroup%20by%EF%BC%8Cjoin%20%E5%88%B0%E5%B7%A5%E5%85%B7%20KNIME/#join)

自己练习下join节点，很简单的

> join 我试过了
但是不行哎    我要把表1 的数据 填充进表2 
join 的结果 表2 很多问好  
问号

> 这个需要理解 left join, right join
